### ISSUE TITLE
Incompatibility Grav 1.7: No |raw for content and assets

### ISSUE THREAD

**Issue by pamtbaau** [hughbris/grav-theme-solarize#12]
Hi Hugh, Hope this finds you well...

Did some `grep`-ing on all themes and found this theme lacking the filter `|raw`, which will render the theme incompatible with Grav 1.7

You may want to take a look at:
- user/themes/solarize/templates/right-sidebar.html.twig:         {{ page.content }}
- user/themes/solarize/templates/left-sidebar.html.twig:            {{ page.content }}
- user/themes/solarize/templates/default.html.twig:                   {{ page.content }}
- user/themes/solarize/templates/partials/base.html.twig:         {{ assets.js() }}
- user/themes/solarize/templates/partials/base.html.twig:         {{ assets.js('init', {'data-theme-root': theme_url} ) }} {# required for pre deferred assets Twig versions, see https://getgrav.org/blog/important-theme-updates #}
- user/themes/solarize/templates/partials/base.html.twig:         {{ assets.css() }}
- user/themes/solarize/templates/partials/base.html.twig:         {{ assets.css('noscript') }}
- user/themes/solarize/templates/partials/base.html.twig:         {{ page.content }}
- user/themes/solarize/templates/partials/base.html.twig:         {{ assets.js('bottom') }}

**Comment by hughbris** [comment]
Thanks again for your heroic efforts. Refer my [comment on landed theme](https://github.com/hughbris/grav-theme-landed/issues/10#issuecomment-1013576864) for response.

**Comment by hughbris** [comment]
@pamtbaau is your grep invocation or checking tool available to verify my changes? I think I got them all.

_Edit: just noticed your list of findings in the issue text, thanks!_

**Comment by pamtbaau** [comment]
My script does not get any hits on branch `v0.2-working`. You should be ok, as long as my script is 100% ;-)
