### ISSUE TITLE
toggle.svg missing

### ISSUE THREAD

**Issue by tiktuk** [hughbris/grav-theme-solarize#4]
`toggle.svg` is missing from the `images` directory.

It's referenced here:

```
#titleBar .toggle:after {
	background: url("images/toggle.svg") 0px 0px no-repeat;
	...
```

**Comment by hughbris** [comment]
Thanks very much for the report. Unfortunately I can't find this SVG file in either original Templated theme download or the [demo](https://templated.co/solarize) and I also can't find a page in the demo where it is used or which uses the id `titleBar`.

If you can find it, please link me to it or attach the file and I will include it in the repo.

**Comment by tiktuk** [comment]
I can't find it either. Thanks for looking though ☺️ .

**Comment by hughbris** [comment]
Yep unfortunately I don't see any way to send bug reports upstream either. Maybe you can source your own.

BTW if you use this theme and want to send me a link, I'll include it in the README as an example in the wild. I'm not using it currently myself.

**Comment by tiktuk** [comment]
Sure, it was more for the sake of not getting 404's. Might send you a link when the site is complete.

Thanks for the theme ☺️ .
