### ISSUE TITLE
Grav 1.6+ Compatibility

### ISSUE THREAD

**Issue by kai47110815** [hughbris/grav-theme-solarize#5]
How does this template work with Grav 1.6+? According to https://getgrav.org/blog/important-theme-updates there are a few changes needed. But the Solarize provided partials/base.html.twig is totally different from the original Quark one. Below is the Solarize base.html.twig:

{% set body_classes = header.body_classes %}
<!DOCTYPE HTML>
<html lang="{{ grav.language.getActive ?: grav.config.site.default_lang }}">
<head>
{% block head %}
	<title>{% if header.title %}{{ header.title|e('html') }} - {% endif %}{{ site.title|default('Solarize by TEMPLATED')|e('html') }}</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	{% include 'partials/metadata.html.twig' %}

	<link rel="icon" type="image/png" href="{{ url('theme://images/favicon.png') }}" />
	<link rel="canonical" href="{{ page.url(true, true) }}" />

	{% block javascripts %}
		{% do assets.addJs('theme://js/jquery.min.js') %}
		{% do assets.addJs('theme://js/jquery.dropotron.min.js') %}
		{% do assets.addJs('theme://js/skel.min.js') %}
		{% do assets.addJs('theme://js/skel-layers.min.js') %}
		{% do assets.addJs('theme://js/init.js', {'group': 'init'} ) %}
	{% endblock %}

	{% block stylesheets %}
		{% if browser.getBrowser == 'msie' and browser.getVersion <= 8 %}
			{# do assets.addJs('theme://css/ie/html5shiv.js', {'group', 'shiv'}) #}
			{% do assets.addJs('theme://css/ie/html5shiv.js') %}
		{% endif %}

		{% do assets.addCss('theme://css/skel.css', {'group': 'noscript'}) %}
		{% do assets.addCss('theme://css/style.css', {'group': 'noscript'}) %}
		{% if browser.getBrowser == 'msie' and browser.getVersion <= 8 %}
			{# do assets.addCss('theme://css/ie/v8.css', {'group', 'ie'}) #}
			{% do assets.addCss('theme://css/ie/v8.css') %}
		{% endif %}
		{% do assets.addCss('theme://css/custom.css') %}
	{% endblock %}

	{{ assets.js() }}
	{{ assets.js('init', { 'data-theme-root': theme_url } ) }}
	{{ assets.css() }}
	<noscript>
		{{ assets.css('noscript') }}
	</noscript>

{% endblock head %}
</head>

<body class="{{ body_classes }}">

	{% block header %}

		
			<div class="wrapper style1">

			
				<div id="header">
					<div class="container">

						
							

						
							<nav id="nav">
								{% include 'partials/navigation.html.twig' %}
							</nav>

					</div>
				</div>

				{% block banner %}{% endblock banner %}

			</div>

	{% endblock header %}

	{% block body %}
		{% block content %}
			{{ page.content }}
		{% endblock content %}
	{% endblock body %}

	{% block footer %}
		{% include 'partials/footer.html.twig' %}
	{% endblock footer %}

	{% block bottom %}
		{{ assets.js('bottom') }}
	{% endblock bottom %}

</body>

**Comment by hughbris** [comment]
Thanks for the notification. I don't think any of the included theme templates require any deferred asset blocks, but of course a developer adding their own templates (e.g. form javascript) might.

If I understand the blog post instructions correctly, I think it will be as simple as surrounding the [`assets` block at line 42](https://github.com/hughbris/grav-theme-solarize/blob/c8c30a74d4daa86b88f69d0f74363b3d4f6e150e/templates/partials/base.html.twig#L42) with a deferred block tag, like:

```twig
{% block assets deferred %}
	{{ assets.js() }}
	{{ assets.js('init', { 'data-theme-root': theme_url } ) }}
	{{ assets.css() }}
	<noscript>
		{{ assets.css('noscript') }}
	</noscript>
{% endblock %}
```

I assume that change will be backwards compatible.

I will implement and test this on the [demo site](https://behold.metamotive.co.nz/solarize) soon. Apart from that one, I don't have any deployed sites using this theme. I'll update the theme and look at my other themes too.

BTW this Solarize theme is not based on Quark at all.

Cheers :)

**Comment by hughbris** [comment]
Hey, the branch `deferred-assets` incorporates 1.6-compatible changes. However, I am unable to test it on either my development machine and server because of minimum Grav/PHP requirements. I thought my server would be OK but it seems not. The deferred block extension to Twig is not backwards compatible, so this change throws an error.

I will make the necessary upgrades after I have planned that process better. On my server, I probably need to upgrade my distribution to safely upgrade to the required PHP version.

Are you able to check out the `deferred-assets` branch and test this for me? If not, I will hold this update back until it can be tested. This could take some time.

**Comment by kai47110815** [comment]
> Hey, the branch `deferred-assets` incorporates 1.6-compatible changes. However, I am unable to test it on either my development machine and server because of minimum Grav/PHP requirements. I thought my server would be OK but it seems not. The deferred block extension to Twig is not backwards compatible, so this change throws an error.
> 
> I will make the necessary upgrades after I have planned that process better. On my server, I probably need to upgrade my distribution to safely upgrade to the required PHP version.
> 
> Are you able to check out the `deferred-assets` branch and test this for me? If not, I will hold this update back until it can be tested. This could take some time.

Checked it, didn't work. Site seems not to load any CSS at all (blank white page with text-only and no formatting).  If it helps, I can you provide a quota on a webserver for your testings and FTP login.  Just make sure, we communicate secure.

**Comment by hughbris** [comment]
Thanks for testing and for the offer. It's likely to be at least another week before I can test this myself, so yes I would like to accept your offer to test it sooner.

You can grab a working email address from either the commit log of this theme or from its blueprint. Or if you need a more secure channel and are on the Grav Discord server, find me with the same username and PM me there.

**Comment by mikegcox** [comment]
From my testing on both my local dev environment and a live DigitalOcean droplet, I find the issue to be line 43 of `base.html.twig`
```
        {{ assets.js('init', { 'data-theme-root': theme_url } ) }}
```
I just don't know how to fix it. When I view source of the working demo, line 43 is rendered as:

```
<script src="/user/sites/solarize/themes/solarize/js/init.js" data-theme-root="/user/sites/solarize/themes/solarize" ></script>
```
What renders in my site is missing the `data-theme-root` string
```
<script src="/user/themes/solarize/js/init.js"></script>
```
If I hard code that tag without using the asset manager, the skin loads fine.  Do I don't think you need the deferred code in there at all.  Just need to figure out how to get this to work: `{ 'data-theme-root': theme_url }`

**Comment by mikegcox** [comment]
I figured it out:
```
{% set body_classes = header.body_classes %}
<!DOCTYPE HTML>
<!--
	Solarize by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html lang="{{ grav.language.getActive ?: grav.config.site.default_lang }}">
<head>
{% block head %}
	<title>{% if header.title %}{{ header.title|e('html') }} - {% endif %}{{ site.title|default('Solarize by TEMPLATED')|e('html') }}</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	{% include 'partials/metadata.html.twig' %}

	<link rel="icon" type="image/png" href="{{ url('theme://images/favicon.png') }}" />
	<link rel="canonical" href="{{ page.url(true, true) }}" />

	{% block javascripts %}
		{% do assets.addJs('theme://js/jquery.min.js') %}
		{% do assets.addJs('theme://js/jquery.dropotron.min.js') %}
		{% do assets.addJs('theme://js/skel.min.js') %}
		{% do assets.addJs('theme://js/skel-layers.min.js') %}
		{% do assets.addJs('theme://js/init.js', {'group': 'init', 'data-theme-root': theme_url} ) %}
	{% endblock %}

	{% block stylesheets %}
		{% if browser.getBrowser == 'msie' and browser.getVersion <= 8 %}
			{# do assets.addJs('theme://css/ie/html5shiv.js', {'group', 'shiv'}) #}
			{% do assets.addJs('theme://css/ie/html5shiv.js') %}
		{% endif %}

		{% do assets.addCss('theme://css/skel.css', {'group': 'noscript'}) %}
		{% do assets.addCss('theme://css/style.css', {'group': 'noscript'}) %}
		{% if browser.getBrowser == 'msie' and browser.getVersion <= 8 %}
			{# do assets.addCss('theme://css/ie/v8.css', {'group', 'ie'}) #}
			{% do assets.addCss('theme://css/ie/v8.css') %}
		{% endif %}
		{% do assets.addCss('theme://css/custom.css') %}
	{% endblock %}

	{{ assets.js() }}
	{{ assets.js('init') }}
	{{ assets.css() }}
	<noscript>
		{{ assets.css('noscript') }}
	</noscript>

{% endblock head %}
</head>

<body class="{{ body_classes }}">

	{% block header %}

		<!-- Header Wrapper -->
			<div class="wrapper style1">

			<!-- Header -->
				<div id="header">
					<div class="container">

						<!-- Logo -->
							<h1><a href="{{ home_url }}" id="logo">{{ site.title }}</a></h1>

						<!-- Nav -->
							<nav id="nav">
								{% include 'partials/navigation.html.twig' %}
							</nav>

					</div>
				</div>

				{% block banner %}{% endblock banner %}

			</div>

	{% endblock header %}

	{% block body %}
		{% block content %}
			{{ page.content }}
		{% endblock content %}
	{% endblock body %}

	{% block footer %}
		{% include 'partials/footer.html.twig' %}
	{% endblock footer %}

	{% block bottom %}
		{{ assets.js('bottom') }}
	{% endblock bottom %}

</body>

```

**Comment by hughbris** [comment]
Yeah that's the one, f7eb795 fixed it.

The version in the [`deferred-assets` branch](https://github.com/hughbris/grav-theme-solarize/tree/deferred-assets) should have worked for you assuming you are on Grav 1.6+. I'm holding that change back in the branch, awaiting an answer from the core developers because it's strange that used to work. I think something else has changed that may need documenting

I don't really like how this theme uses Javascript to load CSS. That's the skel framework it uses, I think. I might look at taking that extra point of failure out if I have time.

Thanks for the report. Send me a link if you want your site included in the list of examples in the README.

**Comment by mikegcox** [comment]
I did try that branch and it didn't seem to work.  Probably my fault, but I will try again.  If you just remove the `init.js` stuff and the remove the `<noscript>` tag around the css assets, the skin works just fine. Maybe I will do that for my project.  Thanks for the Skin... saves me some work.
